import type { Metadata } from "next";
import ScrollAwareNavbar from "./components/ScrollAwareNavbar";
import Footer from "./components/Footer";
import { alliance } from "@/app/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alliance.variable} antialiased bg-[#121212]`}>
        <ScrollAwareNavbar />
        <main className="font-alliance">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
